"""Adding columns to User and Loan model

Revision ID: 2b49dfcb46ac
Revises: ac454f03e938
Create Date: 2025-11-13 13:06:12.456795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b49dfcb46ac'
down_revision = 'ac454f03e938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reason', sa.Text(), nullable=False))
        batch_op.drop_column('application_date')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('reason')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
