"""Add reason to model Loan

Revision ID: 48e631428bb7
Revises: 2b49dfcb46ac
Create Date: 2025-11-13 14:09:57.518945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e631428bb7'
down_revision = '2b49dfcb46ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_loans')
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reason', sa.Text(), nullable=True))
        batch_op.drop_column('application_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('reason')
        batch_op.drop_column('amount')

    op.create_table('_alembic_tmp_loans',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('loan_type', sa.VARCHAR(), nullable=True),
    sa.Column('application_status', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
