"""Adding validation to user

Revision ID: abcec4e8e44b
Revises: d0905c55faf2
Create Date: 2025-11-13 15:14:39.645616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abcec4e8e44b'
down_revision = 'd0905c55faf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
